### PR TITLE
Update 03-rstudio_basics.Rmd

### PR DESCRIPTION
**Pull request by RhoBott**
Trying to avoid: (1) explosions (2) first person plural declaring a singular reality (_omg the feminists..._ I know i know)

### CODE REVIEW

**Review by ismayc — APPROVED** [review]

**Comment by ismayc** [comment]
Thanks much, @RhoBott! A rebuilding of the bookdown book will need to be made as well. I will try to get this automated at some point so that only the changes to the Rmd files are needed for rbasics.netlify.com to be rebuilt.

**Comment by RhoBott** [comment]
Second edit -- adding motivation for moving from Server to Desktop.

**Comment by ismayc** [comment]
I’ll keep this pull request open. Feel free to tag me when your review and tweaks are done.

**Comment by pkq** [comment]
I like both sets of suggestions. Good to avoid anyone exploding! For the first one, how about a slight reorganization of those paragraphs?

> I first learned to use R as a graduate student at Northern Arizona University from [Dr. Philip Turk](http://www.stat.colostate.edu/~pturk/) in 2007. At the time, I never would have thought that students taking an introductory statistics course would be encouraged to learn to use R. Of course, I never imagined that R would become as popular as it has. 

> In 2007, R was still largely an esoteric and tricky language used by statisticians to do analyses. Getting used to the syntax for producing plots and working with data was especially tricky for those with little to no programming experience. Since 2011, the number and diversity of people who use R has grown rapidly. So what has changed about learning R since 2007?

**Comment by ismayc** [comment]
Well, it only took me a little over 6 years, but I'm now working on getting this implemented :). Thanks, @RhoBott and @pkq!

**Comment by ismayc** [comment]
Adding in suggestions from you both into a new commit, and then working with GitHub Actions to get the book to build and deploy to Netlify automatically.

**Pull request closed without merging**
